Traceback (most recent call last):
  File "C:\Users\Adi Sahrul R\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Adi Sahrul R\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adi Sahrul R\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adi Sahrul R\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Adi Sahrul R\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Adi Sahrul R\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Adi Sahrul R\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
raisin = fetch_ucirepo(id=850) 

# data (as pandas dataframes) 
raisin_fitur=raisin.data.features
raisin_class=raisin.data.targets

df_raisin=raisin_fitur.join(raisin_class)

df_raisin.to_csv("raisin.csv", index=False)

#variable features
print(df_raisin)
------------------

----- stdout -----
Collecting ucimlrepo
  Downloading ucimlrepo-0.0.6-py3-none-any.whl.metadata (5.3 kB)
Downloading ucimlrepo-0.0.6-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.6
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 2[0m
[0;32m      1[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mpip install ucimlrepo[39m[38;5;124m'[39m)
[1;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mucimlrepo[39;00m [38;5;28;01mimport[39;00m fetch_ucirepo 
[0;32m      4[0m [38;5;66;03m# fetch dataset [39;00m
[0;32m      5[0m raisin [38;5;241m=[39m fetch_ucirepo([38;5;28mid[39m[38;5;241m=[39m[38;5;241m850[39m) 

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucimlrepo\__init__.py:1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mucimlrepo[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfetch[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucimlrepo\fetch.py:2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mjson[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Optional
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01murllib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrequest[39;00m

[1;31mModuleNotFoundError[0m: No module named 'pandas'

